- README.md
Hi, 
this is heavy-handed in favor of things that relate to HPC;
however there is no reason for not adding more bits in there! (such as autotools, cmake and the like)
enjoy, F.
> added category: Build and software organization tools

- README.md
Apache kafka is a unique message queueing system developed by linked in. It scales to hundreds of thousands of messages per second
> Add Apache Kafka

- README.md
Add the following software repositories:
* [EPEL](https://fedoraproject.org/wiki/EPEL) - Repository for RHEL and compatibles (CentOS, Scientific Linux).
* [Software Collections](https://www.softwarecollections.org) - Community Release of [Red Hat Software Collections](https://access.redhat.com/documentation/en-US/Red_Hat_Software_Collections/). Provides updated packages of Ruby, Python, etc. for CentOS/Scientific Linux 6.x.
* [ElRepo](http://elrepo.org/tiki/tiki-index.php) - Community Repo for Enterprise Linux (RHEL, CentOS, etc).
> Added Repos to Software Repositories

- README.md
Attic is a deduplicating backup program written in Python.
> Add Attic to Backup software

- README.md
[sshrc](https://github.com/Russell91/sshrc) to SSH - sources ~/.sshrc on your local computer after logging in remotely.
> Add sshrc to SSH

- README.md
Spellcheck pass, correcting several mistakes.
Not touched anything debatable - hyphenation, en_US/GB, capitalization etc..
> Spelling Corrections

- README.md
[Glastopf](http://glastopf.org/) is a low interaction honeypot system which emulates vulnerabiltiies to gather data and make sense of the attacks that try to get into your system.
> Add Security -> Glastopf

- README.md
Have added some new virtualization, monitoring, metrics and some XMPP web clients
> Multiple additions

- README.md
Add Elkarbackup in **Backup** category
> Add Elkarbackup

- README.md
Add Open Source project CloudSlang to "Cloud Orchestration" category.
> Add CloudSlang project

- README.md
Added Citadel mail server in "complete solution mail servers" category
> Added Citadel mail server

- README.md
> Addition KDevelop.

- README.md
Great newsletter aggregating the world of devops and operations in a weekly email
> Add weekly devops newsletter resource

- README.md
Linux Malware Detect (LMD or 'maldet') added to Security tools.
[Project Site](https://www.rfxn.com/projects/linux-malware-detect/)
[README that includes License](https://www.rfxn.com/appdocs/README.maldetect)
> Add Linux Malware Detect (LMD)

- README.md
[etcd](https://github.com/coreos/etcd) - distributed, consistent key value store for shared configuration and service discovery
> Add Service discovery -> etcd

- README.md
Bro is a powerful framework for network analysis and security monitoring. 
-> [Github Repo](https://github.com/bro/bro)
-> [Website](http://www.bro.org)
> Add Security -> Bro

- README.md
CC1 is hosted on Github, https://github.com/cc1-cloud/cc1/
> Include Cracow Cloud One

- README.md
https://github.com/cloudtools/ssh-cert-authority
> Add ssh-cert-authority to SSH section

- README.md
Now I will add one app per day, today is Openshift, open source enterprise PaaS powered by Red Hat
> Add Openshift

- README.md
Fixed control panel into subgroups, as mentioned in #67 
@n1trux look if is good to merge.
> Fix control panel

- README.md
web interface to manage postfix mailboxes, virtual domains and aliases.
> Add Postfix Admin

- README.md
Fixes topics order and insert forget topics on list
> Final listing fixes

- README.md
I have used it in the past and would recommend it if you want simple/clean system/storage/network load information for a machine.
> add Linux Dash

- README.md
I've used it successfully in the past. Possible replacement for (urgh) phpmyadmin.
> add adminer

- README.md
Didn't use it myself but other users could provide feedback. It seems pretty popular. ping @opinkerfi
> add adagios

- README.md
Hey, I added some subheadings for the metrics area so you can more easily identify the tools you might be looking for
> Neaten up the metrics area a little

- README.md
Security: Nmap - everything you want in a port scanner and more.
https://nmap.org
Editors: Nano - super easy to use, very customizable.
http://nano-editor.org
> add: nmap and nano

- README.md
Please wait for https://github.com/Kickball/awesome-selfhosted/pull/222 to be merged (the pull request adds lists from your repo). You can preview the results at https://github.com/nodiscc/awesome-selfhosted/tree/freedombox-wiki#email
> move email software to awesome-selfhosted

- README.md
Google Code will shut down in the near future.
Original PR: kahun/awesome-sysadmin#301
> Change Google Code URLs

- README.md
> point wikis section to awesome-selfhosted

- README.md
> Point project management section to awesome-selfhosted

- README.md
Updated website for the project (new one is located at http://cobbler.github.io/ instead of http://www.cobblerd.org/)
> Edited Cobbler website

- README.md
> link to awesome-selfhosted for analytics/statistics software

- README.md
FIR (Fast Incident Response) is a cybersecurity incident management platform designed with agility and speed in mind. It allows for easy creation, tracking, and reporting of cybersecurity incidents. FIR is for anyone needing to track cybersecurity incidents (CSIRTs, CERTs, SOCs, etc.).
> add FIR (Fast Incident Response).

- README.md
https://github.com/Kickball/awesome-selfhosted/issues/127
> remove xmpp section, link awesome-selfhosted

- README.md
I have added a remote management category,
> add Remote Management category with TigerVNC,  Remmina, and X2go

- README.md
It's really fast and easily extensible to monitor anything that is going on in a system.
> Metric & Metric Collection:Dashboards: Add netdata monitoring app/service.

- README.md
> Add OPSI in IT Assets Management Software

- README.md
Add chatops tool [abot](https://github.com/itsabot/abot)
> Add abot in ChatOps

- README.md
https://github.com/Kickball/awesome-selfhosted#file-transfersynchronization
fix some spacing/formatting
> move Cloud Storage section to awesome-selfhosted

- README.md
XenServer is not just plain Xen: it's a complete "turnkey" distro which embed Xen and a powerful toolstack/API. And it's FOSS.
> add XenServer in Virtualization

- README.md
Ref https://github.com/Kickball/awesome-selfhosted/pull/599
excellent software
> Add GoAccess

- README.md
Add [Otto](https://www.ottoproject.io/) to Virtualization section.
Very powerful and promising tool from the creators of Vagrant. Here's a [Changelog Podcast episode](http://5by5.tv/changelog/180), which gives a great intro to the project.
It also does automation, but not sure if you want it listed in multiple sections. Just lemme know! Thanks!
> Add Otto to Virtualization

- README.md
So many awesome tools already on the list.  We wanted to add a few that we use on a regular basis to make Cloud Foundry as awesome as possible.
* Shield
* Genesis
* Spruce
* Concourse
* Bolo
And a link to a book we're actively publishing on GitBook called Codex that puts it all together and shows people how to use them.
> Add Stark & Wayne Tools

- README.md
Transfer the [Federated Identity/Authentication](https://github.com/Kickball/awesome-selfhosted#federated-identityauthentication) section from [Awesome Selfhosted](https://github.com/Kickball/awesome-selfhosted) as discussed in [Awesome-Selfhosted#729](https://github.com/Kickball/awesome-selfhosted/pull/729).
> Transfer Federated Identity/Authentication from Awesome Selfhosted

- README.md
Ref https://github.com/Kickball/awesome-selfhosted/issues/127
MIT Go
> Add Go IPFS

- README.md
Ref https://github.com/Kickball/awesome-selfhosted/issues/127
https://github.com/camlistore/camlistore
Apache Go
> Add Camlistore

- README.md
> Add netbox

- README.md
Ref https://github.com/Kickball/awesome-selfhosted/issues/127
https://bitbucket.org/orifs/ori/wiki/Home
MIT C++
> Add Ori Filesystem

- README.md
It is not awesome as it is not open source.
> Remove Sentry

- README.md
We have a lot of Linux tutorials and guides on our blog useful for sysadmins.
> Add the RoseHosting blog

- README.md
Link was pointing relative to the repository, a 'http' was missing.
> Fixed HPCBIOS Link

- README.md
To me it's the best (and most active project) gui for PowerDNS.
> Add nsedit to DNS control panel

- README.md
DomainMOD is an open source application written in PHP & MySQL used to manage your domains and other internet assets in a central location. DomainMOD also includes a Data Warehouse framework that allows you to import your web server data so that you can view, export, and report on your live data (currently only supports WHM/cPanel servers).
What started out as a personal project to manage my own domains, has now grown into the leading self-hosted domain management application available today.
> Create Domains section and add DomainMOD

- README.md
Would be great if you could add SWMP to the list?
> Add SWMP to "Monitor" Section

- README.md
Hey, 
This pull only add Swarm to the list. 
Thanks
> feat(Docker): Swarm to manage cluster of Docker Engines

- README.md
Otto is no longer be actively maintained or supported. See https://www.ottoproject.io/
> remove otto

- README.md
https://sysadmin.libhunt.com is based on the list here, and is pointing back to this repo as the official one.
> Add 'Awesome SysAdmin @ LibHunt' to the Resources/Websites section

- README.md
PHP Server Monitor is a nice and (well maintained) self hosting monitoring solution.
(If there shold be a link to the code, here it is: https://github.com/phpservermon/phpservermon)
> added PHP Server Monitor to the monitoring section

- README.md
phpipam is an open-source web IP address management application (IPAM). Its goal is to provide light, modern and useful IP address management. It is php-based application with MySQL database backend, using jQuery libraries, ajax and HTML5/CSS3 features.
> added phpIPAM

- README.md
An awesome backup tool with great webinterface.
> Add BackupPC to Backups

- README.md
Add Barman to the backup tool list
> Add Barman to the backup tool list

- README.md
- Updated Nylas Mail URL
- Updated Ganeti URL
- Updated Codex GitBook URL
> Update broken links.

- README.md
GNS3 is graphical network simulator to test complex networks setups.
> GNS3 added to Network Configuration Management

- .github/CONTRIBUTING.md
- README.md
* Fix Markdown according to markdown-lint
* Fix link to CONTRIBUTING.md
> Fix Markdown

- README.md
[Terraform](https://www.terraform.io/) / Cloud Orchestration
https://github.com/hashicorp/terraform
Terraform is awesome.  You write code to create infrastructure.  The tools themselves are modular and as such it has providers that allow creation of infrastructure in AWS, Microsoft Azure, Google Cloud Platform, Oracle, and many others.  Terraform is *the* way that companies try to build multi-cloud solutions.
> add Terraform

- README.md
Update URL for WebSVN and remove Node-Bell, which is a dead project.
> Fix TravisCI Issues

- README.md
Original link was directing to the old repo
> Fix sshuttle link

- README.md
[Pi-hole](https://pi-hole.net/) / DNS
https://pi-hole.net/
Installs on top of Raspbian or Debian, Ubuntu etc to create an internet blackhole for advertisements by managing dnsmasq and giving a very nice front end.
> Add pi-hole

- README.md
Remove Panamax, it appears to be a dead project.
Fix link for Riak, website structure has changed
> Fixes for TravisCI Errors

- README.md
Network flow Monitoring (Netflow, sFlow and IPFIX) with the Elastic Stack
> Add ElastiFlow

- README.md
[Telegraf](https://www.influxdata.com/time-series-platform/telegraf/) / Metric & Metric Collection
https://github.com/influxdata/telegraf
Easy to install and configure plugins, and made my the InfluxDB guys :)
> Add Telegraf

- README.md
Portainer / Software Containers
Should this go under Software Containers or Control Panels?
https://portainer.io/
https://github.com/portainer/portainer
Portainer is an open-source lightweight management UI which allows you to easily manage you docker host or swarm clusters.
> Add portainer

- README.md
[CoreDNS](https://coredns.io/) / DNS
https://github.com/coredns/coredns
CoreDNS is awesome because it is very flexible, simple, can use many external sources of DNS records including etcd and redis.
> Add CoreDNS

- README.md
[Backupninja](https://0xacab.org/riseuplabs/backupninja) / Backups
As you can read here: https://labs.riseup.net/code/projects/backupninja its new repository is: https://0xacab.org/riseuplabs/backupninja
Regards,
> Update BackupNinja URL

- README.md
[Darcs](http://darcs.net) / Version Control
https://hub.darcs.net/darcs/darcs-reviewed
It's really hard to describe Darcs in one short sentence. Hopefully I did it some justice. I included a link to a page that might help explain it or here is another one if you want to see how it compares to Git http://darcs.net/DifferencesFromGit
> Adding Darcs version control

- README.md
[NetXMS](https://www.netxms.org/) / Monitoring
https://github.com/netxms/netxms
Easy to use monitoring and mapping solution
> Add NetXMS Monitoring System

- README.md
[Statusfy](https://statusfy.co) / Status Pages
https://github.com/bazzite/statusfy
This tool is an amazing progressive web app that allows for modern status updates on a status page.
> Add Statusfy under Status Pages.

- README.md
> vigil (Status Pages)

- README.md
[XCP-ng](http://www.xcp-ng.org/) / Virtualization
https://github.com/xcp-ng/xcp
Based on XenServer, XCP-ng is the result of massive cooperation between individuals and companies, to deliver a product without limits. No restrictions on features and every bit available on GitHub!
> Added XCP-ng to virtualization software

- README.md
> Edit: BackupPC Site moved

- README.md
Bolt is akin to PDQ Deploy in the sense that you can run scripts against multiple client types to help configure nodes in an environment. Except that bolt is agentless too!
[awesometool](https://example.com) / Devops
https://github.example.com/repo
This tool is so awesome because it allows me to do awesome things in my
awesome corp, especially when I use it to manage awesome othersoftware.
> Update Readme to include Puppet’s open source Bolt

- README.md
[Smallstep Certifications](https://smallstep.com/certificates/) / Identity Management
https://github.com/smallstep/certificates
Easily manage enterprise-wide distrubtion of X.509 certificates for both TLS-secured services and SSH hosts.
> Add Smallstep Certifications, a personal CA toolkit for SSO TLS & SSH.

- README.md
[eXist-db](https://www.exist-db.org) / NoSQL
https://github.com/eXist-db/exist
Java-based Open Source XML-Database, which supports Xquery, XPath, amm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/n1trux/awesome-sysadmin/326)
> Added eXist-db, XML Database

- README.md
> Backups: Add link to restic/others

- README.md
> Update Concourse website

- README.md
[awesometool](https://example.com) / Devops
https://github.example.com/repo
This tool is so awesome because it allows me to do awesome things in my
awesome corp, especially when I use it to manage awesome othersoftware.
> update OCS link in IT Asset Management

- README.md
[werf](https://werf.io/) / Continuous Integration & Continuous Deployment
https://github.com/werf/werf
Werf is great because it guarantees idempotency & determinism through all CI pipeline, integrates with any CI system of your choice and is compatible with widely used tech stack (Docker, Kubernetes, Helm, GitLab…).
> Adding werf to CI/CD

- README.md
Project 'riseuplabs/backupninja' was moved to 'liberate/backupninja'
> update backupninja link

- README.md
[Scrutiny](https://github.com/AnalogJ/scrutiny) / Monitoring
https://github.com/AnalogJ/scrutiny
Scrutiny is a Hard Drive Health Dashboard & Monitoring solution, merging manufacturer provided S.M.A.R.T metrics with real-world failure rates.
> Add Scrutiny

- README.md
[firezone](https://www.firez.one/) / VPN
https://www.firez.one/
https://github.com/firezone/firezone
* simple management of WireGuard tunnels with a UI
* user-based authentication
> add Firezone to VPN

- README.md
Closes #369 
Closes #372 
Closes #389
> ReadMe Cleanup

- README.md
[awesometool](https://example.com) / Devops
https://github.example.com/repo
This tool is so awesome because it allows me to do awesome things in my
awesome corp, especially when I use it to manage awesome othersoftware.
> Add VictoriaMetrics monitoring system

- README.md
- fixes https://github.com/awesome-foss/awesome-sysadmin/issues/193
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) …
> add aptly to Packaging

- README.md
> change vscode to vscodium

- README.md
I did not use the atom.io link because it seems laggy and error prone when visiting and maybe it'll get taken down.. so I linked to the atom repo that will be archived in a few months
> update atom editor

- README.md
also fix alphabetical issue
Suggested titles: "Add …
> remove rdp wrap as it is dead

- README.md
> SSO Keycloak

- README.md
[Yacht](https://yacht.sh/) - A container management UI with a focus on templates and 1-click deployments.
[Traefik](https://traefik.io/) - Traefik is a leading modern reverse proxy and load balancer.
[RustDesk](https://github.com/rustdesk/rustdesk) - Open source virtual / remote desktop infrastructure to display and control your PC and Android devices from anywhere at anytime.
https://yacht.sh/
https://traefik.io/
https://rustdesk.com/
This tool is so awesome because it allows me to do awesome things in my
awesome corp, especially when I use it to manage awesome other software.
> Add Traefik

- README.md
- this makes the list compatible with https://github.com/nodiscc/hecat for automated checks/maintenance tasks
> improve formatting, use level 3 headings for all categories

- README.md
> Various formatting/cleanup tasks

- README.md
The last release was in 2016 and the Github repo states that the repo was archived (read-only) in 2022.
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), …
> Remove Light Table from Editors (unmaintained)

- README.md
- unmaintained since 2019
- removed from Debian https://tracker.debian.org/pkg/ori, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912175
> remove Ori Filesystem (unmaintained)

- README.md
Criteria for _awesomeness_ should be more clearly defined before we resume adding new projects to the list.
> update description: the project is in minimal maintenance mode

- README.md
- the project is archived
Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
"Remove aaa from bbb" for removing, "Fix license for aaa", etc.
> remove pgobserver (unmaintained since 2020)

- README.md
I had to delete all those books except the only page that actually links to a massive .pdf book for free..
yes to everything
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), …
> remove non free books and broken links

- README.md
> Add OPNsense, OpenWRT and DD-WRT

- README.md
[Woodpecker](https://woodpecker-ci.org/) / Continuous Integration & Continuous Deployment
https://github.com/woodpecker-ci/woodpecker
It's lightweight which makes it easy to self-host.
> Add Woodpecker to list of CI/CD software

- README.md
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), …
> Remove unmaintained projects, add source code links/license/language

- README.md
Ref. https://github.com/awesome-foss/awesome-sysadmin/issues/416, https://github.com/awesome-foss/awesome-sysadmin/issues/405
> monitoring: add missing metadata, fix syntax, remove unmaintained projects

- .github/PULL_REQUEST_TEMPLATE.md
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/357
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/449
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/453
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/457
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3217
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/429
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/377
> pull request template: additional questions to help evaluate actual awesomeness of projects

- README.md
buildah, podman, podman-compose work together under the hood but can be used independently. Because of the close relation, I submit all in one pull request. 
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source …
> Add podman

- README.md
> Add systemd nspawn

- README.md
> Add Status to Monitoring software

- README.md
> Add Authelia to Identity Management - Single Sign-On (SSO)

- README.md
Suggested titles: "Add aaa to bbb" for adding software aaa to section bbb,
"Remove aaa from bbb" for removing, "Fix license for aaa", etc.
--------------
'dar' is much more robust than tar, the maintainer is diligent on fixing errors. 'dar' provides a lot of functionality in a small package and is simple to operate in a restore scenario in the (possibly distant) future.
> Add 'dar' to 'Backups'

- README.md
- Ref. https://github.com/awesome-foss/awesome-sysadmin/issues/405
- Ref. https://github.com/awesome-foss/awesome-sysadmin/issues/416
> Log management: cleanup, formatting, remove unmaintained and non-Free software

- README.md
> log management: add rsyslog

- README.md
- Add source code links, licenses, languages, improve descriptions
- Ref. https://github.com/awesome-foss/awesome-sysadmin/issues/405, https://github.com/awesome-foss/awesome-sysadmin/issues/416
> Cleanup/improve Web section, remove Cherokee and uWSGI 

- README.md
> Fix: Changed Traefik language (C -> Go)

- README.md
Based on this comment: https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3695#issuecomment-1500747594
I'm going to steadily work on addressing: https://github.com/awesome-foss/awesome-sysadmin/issues/416
The format:
```
- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` `Language` 
```
> Automation section: add source code link, license, and language/platform tag

- README.md
> fix link for Remmina

- README.md
> DNS Control Panels: cleanup/formatting

- README.md
> Add JuiceFS to Distributed Filesystems

- README.md
> Metrics & Metric Collection: cleanup, formatting, remove dead links, add licenses/languages

- README.md
This resolves Issue https://github.com/awesome-foss/awesome-sysadmin/issues/398
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), …
> Add Proxmox Backup Server to Backups

- README.md
I don't see any better place to add pfSense other then router, since their is no real Firewall section, however this is for sure a software that should be in this list.
I also changes the `*` to `-` to make it consistent.
This resolves issue https://github.com/awesome-foss/awesome-sysadmin/issues/447
`Demo` links should only be used for interactive demos, i.e. not video …
> Add pfSense CE to Router

- README.md
> Add ruptime to Monitoring

- README.md
> Cleanup, formatting, add source code URLs, licenses, languages

- README.md
> Cleanup, formatting, add licenses/source code links/languages, remove unmaintained projects

- README.md
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/473
> DNS: group Control Panels and Domain Management subsections, cleanup

- README.md
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/473
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3938
> move nsupdate.info/SPF Toolbox from awesome-selfhosted/DNS to DNS - Control Panels & Domain Management

- README.md
- https://github.com/awesome-selfhosted/awesome-selfhosted#dns
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted/pull/3942
> Remove Pi-Hole (moved to awesome-selfhosted/DNS)

- README.md
- [ x] Additions are not already listed at …
> Add authentik to SSO

- README.md
Updated URL for awesome-selfhosted Project Mangement section.
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source Code](http://url.of/source/code), [Clients](https://url.to/list/of/related/clients-or-apps)) `License` …
> Update URL for awesome-selfhosted project-management

- README.md
Cabot last commit is dated from Jan 2021.
Furthermore its code base is not compatible with Python 3.x and requires Python 2.7. Python 2.7 is unmaintained and does no receive security support since 01 Jan 2020
``- [Name](http://homepage/) - Short description, under 250 characters, sentence …
> Remove Cabot (unmaintained)

- README.md
- ref. https://github.com/awesome-foss/awesome-sysadmin/pull/515/
- ref. https://github.com/awesome-foss/awesome-sysadmin/issues/405#issuecomment-1792489284
> Remove VestaCP (unmaintained since 2022)

- README.md
-  This repository has been archived by the owner on Jun 2, 2023. It is now read-only.
> remove GolangCI (the project is archived)

- README.md
-  This repository has been archived by the owner on Aug 9, 2021. It is now read-only.
> remove CapsuleCD (the project is archived)

- .github/PULL_REQUEST_TEMPLATE.md
This is just for documentation purposes as the links are now outdated and i'm fixing them for an accurate resource to refer to as awesome-selfhosted no longer accepts PRs.
> Adjust links for awesome-selfhosted.

- README.md
As per discussed in https://github.com/awesome-foss/awesome-sysadmin/pull/549#pullrequestreview-1847059533, I have fully made the correct fixes. I hope this is everything 💯
> Fix all links to be accurate

- README.md
> Add Static Web Server

- README.md
> add aerc to the list of mail clients

- README.md
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/608
> add PaaS section, move items from awesome-selfhosted

- README.md
> Remove Vlad the Deployer (unmaintained since 2020)

- README.md
- ref. #https://github.com/awesome-foss/awesome-sysadmin/issues/405
> remove Mina (unmaintained since Oct 2023)

- README.md
> remove DrawThe.Net (unmaintained since 2017)

- README.md
> remove perf-tools (unmaintained since 2020)

- README.md
- https://gitlab.com/hsleisink/hiawatha/-/commits/master/?ref_type=HEADS
> remove Hiawatha (unmaintained since Oct 2023)

- README.md
- https://www.tinc-vpn.org/git/browse?p=tinc;a=shortlog
> remove Tinc (unmaintained since 2021)

- README.md
> remove IndieAuth (unmaintained since 2021)

- README.md
Fixed Demo of [Status](https://github.com/dani3l0/Status) from  https://status-ksk5.onrender.com/ to https://status.enshittification.social/
``- [Name](http://homepage/) - Short description, under 250 characters, sentence case. ([Demo](http://url.to/demo), [Source …
> Fixed Demo of Status

- README.md
- ref. https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/814
> move Web Servers section to awesome-selfhosted

- README.md
> Add Terrateam

- README.md
> Add backrest to backups category of README.md

- README.md
Dead Project. Last Release 2020.
https://github.com/backuppc/backuppc/issues/481
- [X ] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [ X] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [X ] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ X] Format your submission as follows, where `Demo` and `Clients` are optional.
Keep the short description under 80 characters and use [sentence …
> Remove BackupPC

- README.md
No commits since May 2023
Last commit was removing the mailing list so seem to be removing features
No FOSS LIcense
> Remove Amanda (Unmaintained since May 2023)

- README.md
> Remove PHPCI and IceCoder due to being Archived

- README.md
bloonix's domain has changed
Suggested titles: "Add …
> Remove Bloonix
