README.md
This is a great data viewer that's originally intended to easily display sensor data from IoT devices, but we have been using this in-house for a while to show disparate JSON data and it has been a joy to use.
Check out the demos at http://freeboard.io/ and see for yourself!
=> Add freeboard to Metrics

README.md
The `fwknop` tool is very useful to protect services on servers via 
single packet authorization.
=> Add link to fwknop

README.md
* [obnam](http://obnam.org/) is a backup tool that supports network backups, GPG encryption, data de-duplication (" If the backup repository already contains a particular chunk of data, it will be re-used, even if it was in another file in an older backup generation."). It is snapshot-based and has an easy to use but powerful command line interface. Obnam backup generations can be mounted as a filesystem.
* ~~[clonezilla](http://clonezilla.org/) - do I need to introduce it - is a disk imaging and cloning tool running as a Live CD/USB. It can be used to move operating systems and other partititons between machines, bare metal or virtual, do full backups of an installed system, and more.~~
* [rdiff-backup](http://www.nongnu.org/rdiff-backup/) is another well known backup tool. It is fast …
=> add more backup tools

README.md
* Added link to rake in the Automation section
* Stripped trailing spaces from several entries.
=> Add rake link, strip trailing spaces

README.md
BorgBackup is a fork of Attic. Attic seams to not be actively maintained anymore. Borg added a tone of new features and many bugfixes.
> * more open, faster paced development (see [issue #1](https://github.com/borgbackup/borg/issues/1))
* lots of attic issues fixed (see [issue #5](https://github.com/borgbackup/borg/issues/5))
* less chunk management overhead (less memory and disk usage for chunks index)
* faster remote cache resync (useful when backing up multiple machines into same repo)
* compression: no, lz4, zlib or lzma compression, adjustable compression levels
* repokey replaces problematic passphrase mode (you can't change the passphrase nor the pbkdf2 iteration count in "passphrase" mode)
* simple sparse file support, great for virtual machine disk files
* can read special files …
=> Add BorgBackup to backup software

README.md
_Graylog_ is no longer known as _Graylog2_ for a while now. :)
=> Change name of Graylog

README.md
PGObserver (https://github.com/zalando/PGObserver) is an open-source monitoring solution for PostgreSQL databases. It covers almost all the metrics provided by the database engine's internal statistics collector, and works out of the box with all PostgreSQL versions (beginning with 9.0) as well as AWS RDS. 
Let me know if you have any questions. :)
=> Added PGObserver to Metric & Metric Collection

README.md
Puppet has changed it's domain from puppetlabs.com to puppet.com
=> Update Puppet domain

README.md
Algernon is a web/application server written in Go with built-in support for:
* HTTP/2
* Lua
* Markdown
* Pongo2 and Amber templates
* Sass or GCSS for styling
* JSX
* BoltDB
* Redis
* PostgreSQL
* MariaDB/MySQL
* rate limiting
* graceful shutdown
* plugins
* users and permissions
http://algernon.roboticoverlords.org/
The only external dependency is `ibreadline`. This makes it easy to drop the executable on a server for quickly sharing some files or setting up a documentation server that uses Markdown backed by git.
Disclaimer: Written by me, but it has 260 stars on GitHub, has an official Homebrew package and I think it works nicely for its use. I use it every day.
=> Add Algernon

README.md
Application name: BounCA
Categories: Identity Management
Link source: https://github.com/repleo/bounca
Link website: https://bounca.org
Why: What gitlab and github do for git, does BounCA for OpenSSL. BounCA allows to manage a complete personal key chain via a web-interface and removes the need of calling the OpenSSL manually. Revoking keys is done via one mouse click including generating revoked certificate lists.
=> Added BounCA SSL tool

README.md
munki should be added, since it's a standard in many macOS environments today.
=> Add munki to Deployment Automation

README.md
FreeIPA is not a tool to manage LDAP directories, but rather it's own LDAP directory (389) with Kerberos and named built in. Similar to Active Directory for *nix.
=> More accurately describe FreeIPA.

README.md
**eZ Server Monitor** is a lightweight and simple dashboard monitor for Linux available in Web and Bash application.
In its Web version, eZ Server Monitor is a PHP script which provides a web page containing information such as the operating system, the number of users connected to the server, the system load, CPU, memory RAM, available disk space, bandwidth usage, and especially the port monitoring services such as FTP, SMTP, Web, etc ...
eZ Server Monitor`sh is a Bash script displays on your console information such as the operating system, system load, CPU, RAM, disk space available, network information, temperatures, etc ...
- Official Website : http://www.ezservermonitor.com
- GitHub for eSM Web : https://github.com/shevabam/ezservermonitor-web
- GitHub for eSM sh : …
=> Add eZ Server Monitor

README.md
Project is retired and shouldn't be used, per their website:
NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE!
The Obnam project is retired. See https://blog.liw.fi/posts/2017/08/13/retiring_obnam/ for more information. Please use another backup solution instead.
NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE! NOTE!
=> Remove Obnam

README.md
This fixes the link to the opsi website, which is currently broken.
=> change opsi link to fix 404

README.md
Added Sheepdog, which is a already mature distributed block storage, S3 Storage and distributed file systems. Created by the japanese NTT and licenced as GPL2.
=> Added Sheepdog distributed file system

README.md
Mozilla has marked Heka as deprecated, and presents Hindsight as the replacement
[Hindsight](http://mozilla-services.github.io/hindsight/) / Log Management
https://github.com/mozilla-services/hindsight
Mozilla considers Hindsight to be a mostly drop-in replacement for Heka. Hindsight is also more performant.
=> Replace Heka with Hindsight

README.md
[EdMon](https://github.com/Edraens/EdMon) / Monitoring
https://github.com/Edraens/EdMon
A command-line monitoring application helping you to check that your hosts and services are available, with notifications support.
=> add edmon simple cli monitoring

README.md
[restic](https://restic.net) / Backup
https://github.com/restic/restic/
Actively developed tool for doing encrypted backups to remote locations. Developed under the BSD 2-clause license.
=> Add restic backup

README.md
SWMP now has it's own domain instead of subdomain silliness so it's easier to maintain & remember.
=> Updated SWMP URL to own domain

README.md
As the title suggests, the tool has been renamed + has a new repo-url.
Happy merging ;-)
=> dripcap has been renamed to genet

README.md
HPE has ditched Eucalyptus, and AppScale people have picked it up. Details at https://en.wikipedia.org/wiki/Eucalyptus_(software)
I have just updated the link to reflect these changes
=> Eucalyptus is now free (or discarded?) from HPE

README.md
Added source code links and languages/licenses for consistency.
Improved descriptions.
Once this is merged https://github.com/Kickball/awesome-selfhosted#continuous-integration can be made a single link redirecting here.
=> Merge "Continuous Integration" section from awesome-selfhosted

README.md
All "Collaborative software" entries have been ported to "Groupware" on awesome-selfhosted
=> Groupware: link to awesome-selfhosted#groupware

README.md
This PR adds the deb.sury.org as new source for an up-to-date LAMP Stack as dotdeb is discontinued for newer PHP Versions: https://www.dotdeb.org/2017/01/27/php-7-1-dotdeb/ behind the deb.sury.org project you can find the author of the official packages more details can be found here: https://deb.sury.org/
For the reason above I have marked the dotdeb site as discontinued or should it be removed from this list?
=> Add deb.sury.org as source for the LAMP Stack

README.md
[Netdata](https://www.netdata.cloud/) / Monitoring
https://github.com/netdata/netdata
Updated the existing entry for Netdata with the current website link and proper description.
Also moved it from under **Metric** > **Dashboards** to **Monitoring** as the correct category.
=> Updated entry for Netdata in README

README.md
[Spack](https://spack.io/) / Build and software organization tools
https://github.com/spack/spack
This tool is awesome because it allows for the installation of multiple versions of the same software to coexist on a system and makes managing software for an HPC environment simple and reproducible.
=> Add entry for spack package manager

README.md
Update dead OCS Inventory link to current valid homepage
=> Update dead link of OCS Inventory

README.md
[Statping](https://github.com/hunterlong/statping) / Status Pages
https://github.com/hunterlong/statping
This tool is so awesome because it allows me to do monitor my company servers and services and development teams can be aware of the situation real time!
=> add statping

README.md
[WireGuard](https://www.wireguard.com/) / VPN
https://git.zx2c4.com/WireGuard/
Wireguard is a new VPN based on elliptic curve crypto (Curve25519, ChaCha20, Poly1305) and public key cryptography. It has a very small attack surface and is extremely fast. It's currently used in production by Mullvad VPN and AzireVPN.
=> Add Wireguard to the VPN section

README.md
[Nebula](https://github.com/slackhq/nebula) / VPN
https://github.com/slackhq/nebula
Nebula is simple and secure VPN for p2p communication. It uses the Noise encryption protocol for encrypting traffic and runs on all major platforms (iOS, Android, Linux, Mac, Windows)
=> Add slackhq/Nebula VPN to list of VPN software

README.md
They changed domains a while ago, official commit here: https://github.com/bloonix/bloonix/commit/ba9b1290fb4c64a6602e0a06d6e5e4e6c7622667
=> Fix the Bloonix URL, original domain is just a 404

README.md
[Mermaid](https://mermaid-js.github.io/mermaid-live-editor/) / Diagramming  
[DrawThe.Net](http://go.drawthe.net/) / Diagramming
MermaidJS: https://github.com/mermaid-js/mermaid-live-editor  
DrawTheNet: https://github.com/cidrblock/drawthe.net
Mermaid has a very easy and quick syntax, making it incredibly useful for throwing together quick diagrams on-the-fly. It also has a decent amount of diagram types, making it pretty versatile. It has a CLI interface you can use locally to generate the diagrams yourself. It integrates with [Grafana](https://grafana.com/) via a plugin.
> **Note**: This is on the [master repo](https://github.com/kahun/awesome-sysadmin#diagramming) that this was forked from, which makes me believe it was on here at one point, but I cannot find neither a commit nor a PR …
=> Add category Diagramming, with tools Mermaid, DrawTheNet, and Diagrams.net

README.md
[CDS](https://ovh.github.io/cds/) / Continuous Integration & Continuous Deployment
https://github.com/ovh/cds
CDS, It is the end-result of 12 years' experience in the field of CI/CD. Familiar with most of the standard tools of the industry, the CDS developers found that none completely matched their expectations regarding the four key aspects they identified (Elastic, Extensible, Flexible, but easy, Self-service). That is what CDS tries to solve. 
More details on their website
=> Adding CDS to CI/CD

README.md
It's been rebranded from Camlistore to Perkeep. The [old url](https://camlistore.org/) redirects, [old Github org](https://github.com/camlistore) renamed, [Wikipedia page](https://en.wikipedia.org/wiki/Perkeep) updated. It's effectively been renamed.
[perkeep](https://perkeep.org/) / Network distributed filesystems
https://github.com/perkeep/perkeep
self-hostable storage, sync, share, search solution
=> Update Camlistore name to Perkeep

README.md
http://just-install.it/ isn't available anymore.
[just-install](https://just-install.github.io/) / Client management
https://github.com/just-install
It's already in the list.
=> Update just-install url

README.md
Diamond has changed repositories so I have updated it.
[Diamond](https://github.com/python-diamond/Diamond) / Metric gathering and display software
https://github.com/python-diamond/Diamond
This tool is so awesome because it’s already on the list and it’s even more awesome to have updated links.
=> Change Diamond repository

README.md
[statping-ng](https://github.com/statping-ng/statping-ng) / Devops
https://github.com/statping-ng/statping-ng
statping was abandonned and statping-ng was the new active fork
=> Change statping for statping-ng (active fork)

README.md
Tool: Monitoring > Icinga
`icinga.org` was no longer reachable.
I updated the link to point to the official website `icinga.com`
=> Updated link to Icinga (icinga.org > icinga.com)

README.md
Just PR to fix the url for awesome-selfhosted project-management category
=> Fix awesome-selfhosted project-management link

README.md
Removed genet from the list, link was broken, I didn't find another repo for this tool.
=> Remove: genet

README.md
Headscale is a community maintained fork of Tailscale VPN, which provides docker image and documentation for self hosting.
[Headscale](https://github.com/juanfont/headscale) / VPN
https://github.com/juanfont/headscale
Headscale is a self hosted version of Tailscale VPN which is simple to use and has ready-to-go OOBE.
It supports SSO, multiple users in a team, monitoring services, etc.
=> Added Headscale VPN

README.md
http://limetext.org/ goes to a spam site not related to the Lime editor
i updated it to https://limetext.github.io/ that actually goes to something related to the editor
=> Update limetext link

README.md
[Nomad](https://www.nomadproject.io) / Cloud Orchestration
https://github.com/hashicorp/nomad
Nomad supports more workloads than Kubernetes, supporting non-containerized executables, Java files, and QEMU. It is lightweight, using only about 1% CPU and 6% RAM on my 1GB model Raspberry Pi 4. On top of that, it is very extensible, with plugins that allow it to do things like orchestrate based on availability of GPU resources.
=> Add Nomad to Cloud Orchestration list

README.md
- Bolo's homepage is a default nginx page. I found https://github.com/huntprod/bolo which looks like the source code, but hasn't had a commit since 2018.
=> remove Bolo (unmaintained, homepage down)

README.md
=> Add source code links, licenses, languages, remove dead links/unmaintained projects

README.md
[Dockovpn](https://dockovpn.io) / Devops
https://github.com/dockovpn/dockovpn
Dockovpn is an out of the box dockerized OpenVPN compatible server, which starts in just a few seconds and runs forever.
I've been sing it since 2019 and find it very helpful as do a lot of other Dockovpn users.
I've ben using it for both: personal and professional setups. Personally, I use it every time I need to virtually place myself elswhere in the world using any virtual private server. For professional setup, we're curently building a cloud hosted solution, which it capable of managing thousands of simultaneous users.
I was capable of running it in a setup with dozens of simultaneous users.
- Extremely easy to use
- Starts up in a few seconds
- Can be used in a stateless mode
- Code gets reviewed from …
=> Add Dockovpn to VPN list

.github/workflows/ci.yml, .hecat/awesome-lint.yml, .hecat/import.yml, .hecat/url-check.yml, .travis.yml, Makefile
- travis CI free plans were discontinued
- CI pipeline is similar to https://github.com/awesome-selfhosted/awesome-selfhosted-data and uses https://github.com/nodiscc/hecat
- the pipeline will not pass until https://github.com/awesome-foss/awesome-sysadmin/issues/416 has been fixed
=> replace travis CI with github actions (check syntax, check links)

README.md
This PR makes the LDAP section compliant with https://github.com/awesome-foss/awesome-sysadmin/issues/416 and removes dead projects as per https://github.com/awesome-foss/awesome-sysadmin/issues/405
* ldap: add missing licenses/language tags
* ldap: add openldap source code link
* ldap: add freeradius source code link
* ldap: add freeIPA source code link
* ldap: add apacheDS source code link
* ldap: add 389DS source code link
* ldap: update openldap description and link
* ldap: remove openDS (website down)
* ldap: remove openDJ (website down)
* ldap: update 389DS/ApacheDS/FreeIPA links and descriptions
=> LDAP: add source code links, licenses, languages, update URLs and descriptions

README.md
Following Issue #405
The domain for this project is now longer available and it hasn't been updated since 2016
=> Remove archipel (unmaintained since 2016)

README.md
Phabricator is no longer maintained as of June 1, 2021. 
https://admin.phacility.com/phame/post/view/11/phacility_is_winding_down_operations/
=> Remove Phabricator

.github/PULL_REQUEST_TEMPLATE.md
The existing link:
> `- [ ] Additions are not already listed at [awesome-selfhosted](https://github.com/awesome-foss/awesome-sysadmin)`
takes you to the wrong repository instead of awesome-selfhosted.
The purpose of this pull request is to rectify this problem, as it caused confusion when searching for duplicates.
=> Fix PR Template repo link leading to itself

README.md
=> Distributed filesystems: add source code links, licenses, languages/platforms, remove unmaintained projects

README.md
=> Service Discovery/Software Containers: add source code links, licenses, language/platform tags, remove dead projects

README.md
- mark as related to awesome-selfhosted/Remote Access (servers and web interfaces)
- ref. https://github.com/awesome-foss/awesome-sysadmin/issues/404
=> Rename Remote Management section to Remote Desktop Clients

README.md
=> Added kroki.io to diagramming chapter

README.md
The original link sent you to a malicious website, this is a PR to remove the old link and replace it with the new official demo link:
https://dash.mauz.dev/
=> Fix demo link for "dashdot" in Monitoring software

README.md
- update descriptions
- remove duplicates
- remove software in Cloud Computing already listed at CNCF landscape
- remove unmaintained software
- add source code links
- merge cloud computing/cloud orchestration sections
- ref. https://github.com/awesome-foss/awesome-sysadmin/issues/455
=> add links to CNCF landscape, various cleanup tasks

README.md
- fix warning/error 'the first tag Cloud Computing points to a tag which redirects to another list'
=> move remaining Cloud Computing items to Deployment Automation

README.md
Updating Links from a non-existent page to the current version.
It's important to mention that the updated page no longer references GitLab CE (FOSS) and only provides links to the paid version. Therefore, we should reconsider whether we still want to include links to the new website version.
Also, update the source code link as the repo moved.
=> Update Links to GitLab CI

README.md
Removes website of Atomia DNS as it is still broken
=> Remove Atomia DNS website

.hecat/url-check.yml
The website `https://community.openvpn.net/` employs Cloudflare as a defense against DDoS attacks. As a consequence, attempting to access the URL consistently leads to a 403 error.
=> Exclude openvpn from url check

README.md
```
curl -I https://ceph.com/
HTTP/1.1 500 Internal Server Error
curl -I https://ceph.com/en/
HTTP/1.1 200 OK
```
=> Fix Ceph URL

.hecat/url-check.yml
Fixes url check not excluding `https://community.openvpn.net` due to a leading slash (hopefully)
=> Remove leading slash from openvpn url check

README.md
Reintroduce Environment Modules software which was removed by 7f947f8. Removal was due to the project being hosted on SourceForge. Project is now primarily managed from GitHub.
Also take this opportunity to clarify name of Lmod software (in the same category).
``- [Name](http://homepage/) - …
=> Add Environment Modules to Build and software organization tools

README.md
- [n/a] Any category you are creating has the …
=> Add Rudder to Configuration Management

README.md
PiVPN is [no longer maintained](https://github.com/pivpn/pivpn/releases/tag/v4.6.0) and maintainer has indicated that no handover will occur.
Refer to #405.
=> Remove deprecated PiVPN

README.md
- already listed at https://landscape.cncf.io/?group=projects-and-products&view-mode=card#app-definition-and-development--streaming-messaging
- add link to CNCF.io/Streaming and Messaging category
=> remove rabbitmq and kafka

README.md
This is just adjusting the url for firezone as the previous one was outdated, citing cert issues. The repo shows the updated url, so it would be appropriate to deploy the fix here. :)
=> Fix URL for Firezone

README.md
- [x ] Your additions are [Free software](https://en.wikipedia.org/wiki/Free_software)
- [ x] Software your are submitting is not your own, unless you have a healthy ecosystem with a few contributors (which aren't your sock puppet accounts).
- [ x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [ x] Format your submission as follows, where `Demo` and `Clients` are optional.
for it, even if the project's webpage or …
=> Add Gluetun to VPN
